POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "mail12@mail.com",
    "passwHash": "1990-20-11",
    "gender": "female"
}

### 200

GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users?page=2&results=5,

### 200

GET http://localhost:5000/api/users/17

### 404

GET http://localhost:5000/api/users/2332